[package]
name = "egui_component"
version = "0.1.0-alpha.2"
edition = "2024"
authors = ["Zehua Yang <march772827981@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["egui", "ui", "component", "ui-kit", "gui"]
description = "Unstyled, headless egui components with granular styling. Includes a fully-customizable styling system with optional pre-configured dark and light themes."
categories = ["gui"]
repository = "https://github.com/March-mitsuki/egui_component"
homepage = "https://github.com/March-mitsuki/egui_component"

[dependencies]
egui_component_style_macros = "0.1.0-alpha.2" # internal

anyhow = "1"
tracing = "0.1"

parking_lot = "0.12"
dashmap = "6"

ttf-parser = "0.25"
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
font-kit = "0.14"

egui = { version = "0.34", features = ["serde"] }
egui_animation = "0.11"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
eframe = "0.34"
tracing-subscriber = { version = "0.3", features = ["env-filter"]}
tracing-appender = "0.2"
wasm-bindgen-futures = "0.4.72"
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3.99", features = ["Window", "Document", "Element", "HtmlElement"] }
